### ISSUE TITLE
Safari's "failure to ship" metric claims it doesn't support some APIs that it actually does

### ISSUE THREAD

**Issue by othermaciej** [GoogleChrome/confluence#163] opened 2017-09-20 22:29 UTC
Here are some APIs that the "failure to ship" metric claims Safari does not support, but which it actually does:

ArrayBuffer.length
CSSStyleDeclaration.cssFloat
DOMException.code
DOMException.message
HTMLElement.offset{Height,Left,Parent,Top,Width}
HTMLElement.style

There are probably others, but these were the most immediately obvious (since these are either super old APIs).

The data would be more useful without these errors.

**Comment by foolip** [comment] 2017-09-20 22:42
Thanks for reporting, this is great! I can confirm that `ArrayBuffer.length` is 1 in the Safari 10.1 currently on BrowserStack, either there was an earlier release that was different or there's a problem with the methodology.

One very relevant thing is that `Object.getOwnPropertyNames(ArrayBuffer)` doesn't include "length", so perhaps there's no way to discover that it exists?

Somewhat relatedly, `Object.getOwnPropertyNames(new ArrayBuffer)` includes "byteLength", which points to the general problem that some things can only be seen on instances, and that the tooling doesn't create instances of everything.

**Comment by foolip** [comment] 2017-09-20 22:48
HTMLElement.offset* is because they were on Element before, @cdumez fixed that in https://trac.webkit.org/changeset/216466/webkit/trunk/Source/WebCore/html/HTMLElement.idl

**Comment by foolip** [comment] 2017-09-20 22:48
@mdittmer, can you investigate the remaining ones?

**Comment by mdittmer** [comment] 2017-09-21 13:11
We grab some data from instances by walking the object graph from `window`, and copying instance data to its prototype API. Obviously, this misses lots of potential "instance-only" cases such as `ArrayBuffer`

**Comment by foolip** [comment] 2017-09-21 15:26
Yep, let's get Safari 11 data in https://github.com/GoogleChrome/confluence/issues/162, going through lists of issues that have already been fixed is no fun for anyone.

For "byteLength" and other cases of prototype vs. instance, it's definitely not something that is likely to cause real problems, but it is an actual difference, and if it's not skewing the data in huge ways (like https://github.com/GoogleChrome/confluence/issues/174) then it's probably OK to just leave these in? @othermaciej, WDYT?

**Comment by othermaciej** [comment] 2017-09-21 18:14
@foolip I think it would be helpful to track minor differences in how a property is exposed, but perhaps separately from whether it is present at all. I say this from the point of view of prioritizing implementation tasks. If we're missing a property that all other browsers have entirely, that's a much bigger deal than whether it is exposed via all the same introspection methods. In the case of ArrayBuffer it was immediately clear to me what was happening, but for APIs I am less familiar with, I'd have to do research to know if it was a substantive problem or just about exposure details.

**Comment by foolip** [comment] 2017-09-22 13:07
@othermaciej, I agree, from a prioritization point of view it doesn't make sense to treat instance-vs-prototype problems the same as entirely missing API surface, let's try to work something out here.

@mdittmer, is there a generic bug about making sure we find instances for more interfaces? I think one very basic thing we could do after the graph traversal is done would be to try to invoke everything that looks like an interfaces object as a constructor with no arguments. It'd work for ArrayBuffer at least.

I think we had lots of problems with prototype-vs-instance for attributes, but maybe one thing we could do is to start recording what things exist on prototype vs instance, maybe so that we'd have: Event.NONE (const/static), Event.prototype.bubbles and Event.instance.isTrusted. I'm sure that would result in lots of boring differences, so maybe it could be mangled for metrics, but be exposed with a "boring mode" checkbox in the data explorer?

**Comment by mdittmer** [comment] 2017-09-26 14:20
@othermaciej here are some updates on the APIs originally identified. This is with respect to new data recently pushed from Safari 11:

ArrayBuffer.byteLength -- marked as shipped on Safari 11, but not Safari < 11; I suspect this is related to the fact that we do not instantiate an ArrayBuffer and check its properties; Rick has filed #200 regarding additional data collection from instances
CSSStyleDeclaration.cssFloat -- this should also be picked up by copying instance values onto its prototype's API surface; i.e.,`document.body.style.__proto__ === CSSStyleDeclaration.prototype`; covered by #200
DOMException.code -- this is not on `DOMException.prototype`; we would need to generate a DOMException to discover this API using object graph analysis; covered by #200
DOMException.message -- as above
HTMLElement.offset{Height,Left,Parent,Top,Width} -- this is now showing up on Safari 11; it shows up on `Element` in Safari < 11
HTMLElement.style -- as above

**Comment by RByers** [comment] 2017-09-26 15:12
Note that `DOMException` is a Safari bug which appears fixed in the latest WebKit nightly, perhaps as a side effect of @cdumez's [recent change](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/dom/DOMException.idl?rev=219730).  We can hack around the bug with #200, but given that it's fixed in WebKit trunk I'm not sure it's worth it.

**Comment by RByers** [comment] 2017-09-26 15:22
`cssFloat` is really weird - appears to be a [bug in WebKit](https://bugs.webkit.org/show_bug.cgi?id=177487).  We could add a hack specific to discovering that this property exists despite being entirely hidden from all enumeration, but should we?

**Comment by cdumez** [comment] 2017-09-26 16:35
I made DOMException spec-compliant via:
- https://trac.webkit.org/changeset/219607/webkit
- https://trac.webkit.org/changeset/219663/webkit

This is indeed fairly recent.

**Comment by RByers** [comment] 2017-09-26 17:50
@cdumez, thanks!  I missed those changes since I was looking only at `DOMException.idl` history.

**Comment by RByers** [comment] 2017-09-26 17:57
@mdittmer has now fixed a number of issues here.  I've done a pass through the latest [Safari 11 failure to ship APIs](http://web-confluence.appspot.com/#!/catalog?releaseKeys=%5B%22Safari_11.0_OSX_10.12.6%22,%22Safari_10.1.2_OSX_10.12.6%22,%22Safari_5.1.9_OSX_10.6.8%22,%22Safari_6.0.5_OSX_10.7.5%22,%22Safari_6.2.8_OSX_10.8.5%22,%22Safari_7.1.8_OSX_10.9.5%22,%22Safari_8.0.8_OSX_10.10.5%22,%22Safari_9.1.3_OSX_10.11.6%22,%22Chrome_54.0.2840.59_Windows_10.0%22,%22Chrome_55.0.2883.75_Windows_10.0%22,%22Chrome_56.0.2924.87_Windows_10.0%22,%22Chrome_57.0.2987.110_Windows_10.0%22,%22Chrome_58.0.3029.81_Windows_10.0%22,%22Chrome_59.0.3071.86_Windows_10.0%22,%22Chrome_60.0.3112.78_Windows_10.0%22,%22Chrome_61.0.3163.79_Windows_10.0%22,%22Firefox_49.0_OSX_10.11%22,%22Firefox_50.0_OSX_10.11%22,%22Firefox_51.0_OSX_10.11%22,%22Firefox_52.0_OSX_10.11%22,%22Firefox_53.0_OSX_10.11%22,%22Firefox_54.0_OSX_10.11%22,%22Firefox_55.0_OSX_10.11%22,%22Edge_15.15063_Windows_10.0%22%5D&releaseOptions=%7B%22Safari_11.0_OSX_10.12.6%22:false,%22Safari_10.1.2_OSX_10.12.6%22:false,%22Safari_5.1.9_OSX_10.6.8%22:false,%22Safari_6.0.5_OSX_10.7.5%22:false,%22Safari_6.2.8_OSX_10.8.5%22:false,%22Safari_7.1.8_OSX_10.9.5%22:false,%22Safari_8.0.8_OSX_10.10.5%22:false,%22Safari_9.1.3_OSX_10.11.6%22:false,%22Chrome_54.0.2840.59_Windows_10.0%22:true,%22Chrome_55.0.2883.75_Windows_10.0%22:true,%22Chrome_56.0.2924.87_Windows_10.0%22:true,%22Chrome_57.0.2987.110_Windows_10.0%22:true,%22Chrome_58.0.3029.81_Windows_10.0%22:true,%22Chrome_59.0.3071.86_Windows_10.0%22:true,%22Chrome_60.0.3112.78_Windows_10.0%22:true,%22Chrome_61.0.3163.79_Windows_10.0%22:true,%22Firefox_49.0_OSX_10.11%22:true,%22Firefox_50.0_OSX_10.11%22:true,%22Firefox_51.0_OSX_10.11%22:true,%22Firefox_52.0_OSX_10.11%22:true,%22Firefox_53.0_OSX_10.11%22:true,%22Firefox_54.0_OSX_10.11%22:true,%22Firefox_55.0_OSX_10.11%22:true,%22Edge_15.15063_Windows_10.0%22:true%7D&numAvailable=null&currentPage=0&gap=5&itemPerPage=15&searchKey=%22%22), and other than a couple issues with RegExp (#202, #203) and CSS property aliases (#201) I don't see anything else obviously wrong at a glance (though there's probably still a couple small things I'm missing).  As discussed above there are a few minor bugs we could hide with #200, but as long as there is only a handful I suggest we don't consider them urgent (they are real bugs, so as long as they don't skew the numbers much I'd rather leave them).

@othermaciej (or @cdumez), do you want to take another scan through the list and let us know if you see anything else you believe is incorrect?

**Comment by RByers** [comment] 2017-09-26 18:38
In https://github.com/GoogleChrome/confluence/issues/162#issuecomment-332291147 @othermaciej says:

> From spot-checking the list of claimed "failure to ship" for Safari 11, I don't see anything obviously wrong, but I didn't do any testing or study of the code to confirm (yet).

So let's consider this bug fixed and file new bugs for anything else we discover.

**Closed by RByers** 2017-09-26 18:38 UTC
Labels: bug, failure to ship
